"""SuperAgent S-ABAC configuration.

This module defines the default security attributes used by the policy engine.
The model follows the design in S-ABAC设计.md:

- Subject is governed by department + job_role + grants
- Agent represents a responsibility domain
- Tool inherits the baseline policy of its owner agent
- Scenario fit is evaluated alongside hard ABAC constraints
"""

from __future__ import annotations

SENSITIVITY_LEVELS = {
    "LOW": 1,
    "MEDIUM": 2,
    "HIGH": 3,
    "CRITICAL": 4,
}


DEFAULT_SUBJECT_ATTRIBUTES = {
    "role": "UniversalAssistant",
    "department": "General",
    "job_role": "general_staff",
    "clearance_level": 2,
    "trust_level": "MEDIUM",
    "grants": [],
}


SYSTEM_SUBJECT_ATTRIBUTES = {
    "role": "UniversalAssistant",
    "department": "System",
    "job_role": "system_orchestrator",
    "clearance_level": 5,
    "trust_level": "HIGH",
    "grants": ["all"],
}


AGENT_SECURITY_ATTRIBUTES = {
    "researcher": {
        "role": "ResearchAgent",
        "department": "Research",
        "job_role": "research_analyst",
        "clearance_level": 2,
        "trust_level": "MEDIUM",
        "grants": ["research_read"],
    },
    "coder": {
        "role": "CodeAgent",
        "department": "Engineering",
        "job_role": "engineer",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["code_execute", "file_write"],
    },
    "browser": {
        "role": "BrowserAgent",
        "department": "Research",
        "job_role": "research_assistant",
        "clearance_level": 2,
        "trust_level": "MEDIUM",
        "grants": ["web_access"],
    },
    "reporter": {
        "role": "ReportAgent",
        "department": "General",
        "job_role": "report_specialist",
        "clearance_level": 2,
        "trust_level": "MEDIUM",
        "grants": ["report_generate"],
    },
    "RemoteHRAssistantAgent": {
        "role": "HRAgent",
        "department": "HR",
        "job_role": "hr_service_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["employee_profile_read"],
    },
    "RemoteOfficeAssistantAgent": {
        "role": "OperationAgent",
        "department": "Office",
        "job_role": "office_operations_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["leave_write", "travel_write"],
    },
    "RemoteDocumentGeneratorAgent": {
        "role": "DocumentAgent",
        "department": "Office",
        "job_role": "document_specialist_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["document_generate"],
    },
    "RemoteEmailDispatchAgent": {
        "role": "CommunicationAgent",
        "department": "Office",
        "job_role": "communication_dispatch_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["external_send"],
    },
    "RemoteCommunicationAgent": {
        "role": "CommunicationAgent",
        "department": "Office",
        "job_role": "communication_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["message_send", "notification_send"],
    },
    "RemoteKnowledgeAgent": {
        "role": "KnowledgeAgent",
        "department": "HR",
        "job_role": "knowledge_agent",
        "clearance_level": 2,
        "trust_level": "HIGH",
        "grants": ["knowledge_read"],
    },
    "RemoteBusinessRiskAgent": {
        "role": "RiskAgent",
        "department": "Risk",
        "job_role": "risk_analysis_agent",
        "clearance_level": 4,
        "trust_level": "HIGH",
        "grants": ["risk_analysis", "risk_export"],
    },
    "RemoteUnicornSelectorAgent": {
        "role": "ResearchAgent",
        "department": "Business",
        "job_role": "business_research_agent",
        "clearance_level": 2,
        "trust_level": "MEDIUM",
        "grants": ["research_read"],
    },
    "RemoteReportAgent": {
        "role": "ReportAgent",
        "department": "Business",
        "job_role": "report_specialist_agent",
        "clearance_level": 2,
        "trust_level": "MEDIUM",
        "grants": ["report_generate"],
    },
    "RemoteMeetingManagerAgent": {
        "role": "OperationAgent",
        "department": "Office",
        "job_role": "meeting_operations_agent",
        "clearance_level": 3,
        "trust_level": "HIGH",
        "grants": ["meeting_write"],
    },
}


DEFAULT_OBJECT_ATTRIBUTES = {
    "type": "tool",
    "protocol": "local",
    "sensitivity": "LOW",
    "allowed_roles": [],
    "allowed_job_roles": [],
    "allowed_operation_modes": [],
    "scenario_tags": [],
    "expected_capabilities": [],
    "department_domain": "General",
    "capability_domain": "General",
    "owner_agent": "",
    "requires_approval": False,
    "grants_required": [],
}


RESOURCE_SECURITY_ATTRIBUTES = {
    "researcher": {
        "type": "agent",
        "department_domain": "Research",
        "capability_domain": "Research",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "ResearchAgent", "HRAgent", "CodeAgent", "CommunicationAgent"],
        "allowed_job_roles": [
            "research_analyst",
            "research_assistant",
            "engineer",
            "hr_manager",
            "communication_officer",
            "system_orchestrator",
        ],
        "allowed_operation_modes": ["delegate", "read", "query"],
        "scenario_tags": ["research", "market_research", "knowledge_lookup"],
        "expected_capabilities": ["Research"],
    },
    "coder": {
        "type": "agent",
        "department_domain": "Engineering",
        "capability_domain": "Engineering",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["UniversalAssistant", "CodeAgent"],
        "allowed_job_roles": ["engineer", "senior_engineer", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "execute", "write"],
        "scenario_tags": ["coding", "automation", "debug"],
        "expected_capabilities": ["Engineering"],
    },
    "browser": {
        "type": "agent",
        "department_domain": "Research",
        "capability_domain": "Research",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "BrowserAgent", "ResearchAgent", "CodeAgent"],
        "allowed_job_roles": ["research_analyst", "research_assistant", "engineer", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "query"],
        "scenario_tags": ["research", "web_lookup", "knowledge_lookup"],
        "expected_capabilities": ["Research"],
    },
    "reporter": {
        "type": "agent",
        "department_domain": "General",
        "capability_domain": "Document",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "ReportAgent", "ResearchAgent", "HRAgent", "CodeAgent", "CommunicationAgent"],
        "allowed_job_roles": [
            "report_specialist",
            "research_analyst",
            "hr_manager",
            "engineer",
            "communication_officer",
            "system_orchestrator",
        ],
        "allowed_operation_modes": ["delegate", "generate"],
        "scenario_tags": ["reporting", "analysis_summary", "document_generation"],
        "expected_capabilities": ["Document"],
    },
    "RemoteHRAssistantAgent": {
        "type": "agent",
        "department_domain": "HR",
        "capability_domain": "HR",
        "sensitivity": "HIGH",
        "allowed_roles": ["UniversalAssistant", "HRAgent"],
        "allowed_job_roles": ["hr_specialist", "hr_manager", "hr_bp", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "read", "query"],
        "scenario_tags": ["hr_service", "employee_info", "salary_query", "employee_proof"],
        "expected_capabilities": ["HR"],
    },
    "RemoteDocumentGeneratorAgent": {
        "type": "agent",
        "department_domain": "Office",
        "capability_domain": "Document",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["UniversalAssistant", "HRAgent", "DocumentAgent", "CommunicationAgent"],
        "allowed_job_roles": [
            "hr_specialist",
            "hr_manager",
            "communication_officer",
            "document_specialist",
            "system_orchestrator",
        ],
        "allowed_operation_modes": ["delegate", "generate"],
        "scenario_tags": ["document_generation", "employee_proof", "notification_document"],
        "expected_capabilities": ["Document"],
    },
    "RemoteEmailDispatchAgent": {
        "type": "agent",
        "department_domain": "Office",
        "capability_domain": "Communication",
        "sensitivity": "HIGH",
        "allowed_roles": ["UniversalAssistant", "CommunicationAgent"],
        "allowed_job_roles": ["communication_officer", "communication_manager", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "send"],
        "scenario_tags": ["notification_send", "mass_notification", "external_send"],
        "expected_capabilities": ["Communication"],
        "require_working_hours": True,
        "require_internal_network": True,
    },
    "RemoteCommunicationAgent": {
        "type": "agent",
        "department_domain": "Office",
        "capability_domain": "Communication",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["UniversalAssistant", "CommunicationAgent"],
        "allowed_job_roles": ["communication_officer", "communication_manager", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "send", "generate"],
        "scenario_tags": ["notification_send", "communication", "contact_lookup"],
        "expected_capabilities": ["Communication"],
    },
    "RemoteKnowledgeAgent": {
        "type": "agent",
        "department_domain": "HR",
        "capability_domain": "Knowledge",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "KnowledgeAgent", "HRAgent", "ResearchAgent"],
        "allowed_job_roles": ["hr_specialist", "hr_manager", "research_analyst", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "query"],
        "scenario_tags": ["knowledge_lookup", "policy_lookup", "hr_service"],
        "expected_capabilities": ["Knowledge", "Research"],
    },
    "RemoteBusinessRiskAgent": {
        "type": "agent",
        "department_domain": "Risk",
        "capability_domain": "Risk",
        "sensitivity": "HIGH",
        "allowed_roles": ["UniversalAssistant", "RiskAgent"],
        "allowed_job_roles": ["risk_analyst", "risk_manager", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "read", "query", "export"],
        "scenario_tags": ["risk_analysis", "compliance_review", "credit_risk"],
        "expected_capabilities": ["Risk"],
    },
    "RemoteUnicornSelectorAgent": {
        "type": "agent",
        "department_domain": "Business",
        "capability_domain": "Research",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "ResearchAgent"],
        "allowed_job_roles": ["research_analyst", "business_analyst", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "query"],
        "scenario_tags": ["market_research", "target_selection"],
        "expected_capabilities": ["Research"],
    },
    "RemoteReportAgent": {
        "type": "agent",
        "department_domain": "Business",
        "capability_domain": "Document",
        "sensitivity": "LOW",
        "allowed_roles": ["UniversalAssistant", "ReportAgent"],
        "allowed_job_roles": ["report_specialist", "business_analyst", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "generate"],
        "scenario_tags": ["reporting", "analysis_summary"],
        "expected_capabilities": ["Document"],
    },
    "RemoteMeetingManagerAgent": {
        "type": "agent",
        "department_domain": "Office",
        "capability_domain": "Operations",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["UniversalAssistant", "OperationAgent"],
        "allowed_job_roles": ["office_operator", "office_manager", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "write"],
        "scenario_tags": ["meeting_management", "office_operation"],
        "expected_capabilities": ["Operations"],
    },
    "RemoteOfficeAssistantAgent": {
        "type": "agent",
        "department_domain": "Office",
        "capability_domain": "Operations",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["UniversalAssistant", "OperationAgent", "CommunicationAgent"],
        "allowed_job_roles": ["office_operator", "office_manager", "communication_officer", "hr_manager", "system_orchestrator"],
        "allowed_operation_modes": ["delegate", "write", "query"],
        "scenario_tags": ["leave_request", "travel_request", "office_operation"],
        "expected_capabilities": ["Operations"],
    },
    "tavily_search_results_json": {
        "owner_agent": "researcher",
        "capability_domain": "Research",
        "department_domain": "Research",
        "sensitivity": "LOW",
        "allowed_roles": ["ResearchAgent", "UniversalAssistant"],
        "allowed_job_roles": ["research_analyst", "research_assistant", "engineer", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["research", "knowledge_lookup", "market_research"],
        "expected_capabilities": ["Research"],
    },
    "crawl_tool": {
        "owner_agent": "researcher",
        "capability_domain": "Research",
        "department_domain": "Research",
        "sensitivity": "LOW",
        "allowed_roles": ["ResearchAgent", "UniversalAssistant"],
        "allowed_job_roles": ["research_analyst", "research_assistant", "engineer", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["research", "web_lookup", "market_research"],
        "expected_capabilities": ["Research"],
    },
    "python_repl": {
        "owner_agent": "coder",
        "capability_domain": "Engineering",
        "department_domain": "Engineering",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["CodeAgent", "UniversalAssistant"],
        "allowed_job_roles": ["engineer", "senior_engineer", "system_orchestrator"],
        "allowed_operation_modes": ["execute", "write"],
        "scenario_tags": ["coding", "automation", "debug"],
        "expected_capabilities": ["Engineering"],
    },
    "bash": {
        "owner_agent": "coder",
        "capability_domain": "Engineering",
        "department_domain": "Engineering",
        "sensitivity": "HIGH",
        "allowed_roles": ["CodeAgent", "UniversalAssistant"],
        "allowed_job_roles": ["engineer", "senior_engineer", "system_orchestrator"],
        "allowed_operation_modes": ["execute", "write"],
        "scenario_tags": ["coding", "automation", "debug"],
        "expected_capabilities": ["Engineering"],
        "requires_approval": True,
    },
    "browser": {
        "owner_agent": "browser",
        "capability_domain": "Research",
        "department_domain": "Research",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["BrowserAgent", "ResearchAgent", "UniversalAssistant"],
        "allowed_job_roles": ["research_analyst", "research_assistant", "engineer", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["web_lookup", "research", "knowledge_lookup"],
        "expected_capabilities": ["Research"],
    },
    "write_file": {
        "owner_agent": "coder",
        "capability_domain": "Document",
        "department_domain": "Engineering",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["CodeAgent", "DocumentAgent", "UniversalAssistant"],
        "allowed_job_roles": ["engineer", "document_specialist", "system_orchestrator"],
        "allowed_operation_modes": ["write", "generate"],
        "scenario_tags": ["coding", "document_generation"],
        "expected_capabilities": ["Engineering", "Document"],
    },
    "remote_person_info_tool": {
        "owner_agent": "RemoteHRAssistantAgent",
        "capability_domain": "HR",
        "department_domain": "HR",
        "sensitivity": "HIGH",
        "allowed_roles": ["HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["hr_specialist", "hr_manager", "hr_bp", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["hr_service", "employee_info"],
        "expected_capabilities": ["HR"],
        "grants_required": ["employee_profile_read"],
    },
    "remote_salary_info_tool": {
        "owner_agent": "RemoteHRAssistantAgent",
        "capability_domain": "HR",
        "department_domain": "HR",
        "sensitivity": "HIGH",
        "allowed_roles": ["HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["hr_manager", "hr_bp", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["hr_service", "salary_query", "employee_proof"],
        "expected_capabilities": ["HR"],
        "grants_required": ["salary_read"],
        "requires_approval": True,
    },
    "remote_docx_generator_tool": {
        "owner_agent": "RemoteDocumentGeneratorAgent",
        "capability_domain": "Document",
        "department_domain": "Office",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["DocumentAgent", "HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["hr_specialist", "hr_manager", "document_specialist", "communication_officer", "system_orchestrator"],
        "allowed_operation_modes": ["generate"],
        "scenario_tags": ["document_generation", "employee_proof", "notification_document"],
        "expected_capabilities": ["Document"],
    },
    "remote_email_tool": {
        "owner_agent": "RemoteEmailDispatchAgent",
        "capability_domain": "Communication",
        "department_domain": "Office",
        "sensitivity": "HIGH",
        "allowed_roles": ["CommunicationAgent", "UniversalAssistant"],
        "allowed_job_roles": ["communication_officer", "communication_manager", "system_orchestrator"],
        "allowed_operation_modes": ["send"],
        "scenario_tags": ["notification_send", "mass_notification", "external_send"],
        "expected_capabilities": ["Communication"],
        "grants_required": ["external_send"],
        "require_working_hours": True,
        "require_internal_network": True,
        "requires_approval": True,
        "irreversible": True,
    },
    "knowledge_search_tool": {
        "owner_agent": "RemoteKnowledgeAgent",
        "capability_domain": "Knowledge",
        "department_domain": "HR",
        "sensitivity": "MEDIUM",
        "allowed_roles": ["KnowledgeAgent", "HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["hr_specialist", "hr_manager", "research_analyst", "system_orchestrator"],
        "allowed_operation_modes": ["query", "read"],
        "scenario_tags": ["knowledge_lookup", "policy_lookup", "hr_service"],
        "expected_capabilities": ["Knowledge", "Research"],
    },
    "save_leave_record": {
        "owner_agent": "RemoteOfficeAssistantAgent",
        "capability_domain": "Operations",
        "department_domain": "Office",
        "sensitivity": "HIGH",
        "allowed_roles": ["OperationAgent", "HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["office_operator", "office_manager", "hr_manager", "system_orchestrator"],
        "allowed_operation_modes": ["write", "update"],
        "scenario_tags": ["leave_request"],
        "expected_capabilities": ["Operations"],
        "requires_approval": True,
    },
    "save_travel_record": {
        "owner_agent": "RemoteOfficeAssistantAgent",
        "capability_domain": "Operations",
        "department_domain": "Office",
        "sensitivity": "HIGH",
        "allowed_roles": ["OperationAgent", "HRAgent", "UniversalAssistant"],
        "allowed_job_roles": ["office_operator", "office_manager", "hr_manager", "system_orchestrator"],
        "allowed_operation_modes": ["write", "update"],
        "scenario_tags": ["travel_request"],
        "expected_capabilities": ["Operations"],
        "requires_approval": True,
    },
}


S_ABAC_POLICIES = [
    {
        "policy_id": "P-SYSTEM-ORCHESTRATE-AGENTS",
        "description": "The system orchestrator can delegate to registered agents.",
        "rules": [
            {
                "condition": {
                    "all": [
                        {"subject.subject_type": "system"},
                        {"action.verb": "orchestrate"},
                        {"object.attributes.type": "agent"},
                    ]
                },
                "effect": "ALLOW",
                "constraints": {
                    "allowed_actions": ["delegate"],
                },
            }
        ],
    },
    {
        "policy_id": "P-HR-MANAGER-SALARY",
        "description": "Only HR manager level roles can access salary-sensitive tools in matching HR scenarios.",
        "rules": [
            {
                "condition": {
                    "all": [
                        {"object.id": "remote_salary_info_tool"},
                        {"subject.attributes.job_role": ["hr_manager", "hr_bp", "system_orchestrator"]},
                        {"scenario.task_scenario.task_type": "HR"},
                    ]
                },
                "effect": "ALLOW",
                "constraints": {
                    "allowed_actions": ["call", "query", "read", "execute"],
                },
            }
        ],
    },
    {
        "policy_id": "P-COMMUNICATION-EXTERNAL-SEND",
        "description": "Communication officers can send external emails only in matching communication scenarios.",
        "rules": [
            {
                "condition": {
                    "all": [
                        {"object.id": "remote_email_tool"},
                        {"subject.attributes.job_role": ["communication_officer", "communication_manager", "system_orchestrator"]},
                        {"scenario.task_scenario.task_type": "COMMUNICATION"},
                    ]
                },
                "effect": "ALLOW",
                "constraints": {
                    "allowed_actions": ["send", "call", "execute"],
                    "require_working_hours": True,
                    "require_internal_network": True,
                },
            }
        ],
    },
]
